menloresearch/model-catalog

.github/workflows/update-model-catalog.yml
prepare_catalog.py

ci: add github actions workflow to automate model catalog updates

ci: add github actions workflow to automate model catalog updates

---

script_output.log

- **New models added:** 0
- **Total models in catalog:** 206

🤖 Auto-update Model Catalog - 19-07-2025 02:38

---

model_catalog.json
script_output.log

- **New models added:** 7
- **Total models in catalog:** 261

🤖 Auto-update Model Catalog - 24-07-2025 02:41

---

model_catalog.json
script_output.log

- **New models added:** 78
- **Total models in catalog:** 201

🤖 Auto-update Model Catalog - 25-07-2025 02:41

---

model_catalog.json
script_output.log

- **New models added:** 77
- **Total models in catalog:** 212

🤖 Auto-update Model Catalog - 29-07-2025 02:48

---

model_catalog.json
script_output.log

- **New models added:** 75
- **Total models in catalog:** 219

🤖 Auto-update Model Catalog - 30-07-2025 02:44

---

model_catalog.json
script_output.log

- **New models added:** 69
- **Total models in catalog:** 231

🤖 Auto-update Model Catalog - 02-08-2025 02:38

---

model_catalog.json
script_output.log

- **New models added:** 68
- **Total models in catalog:** 238

🤖 Auto-update Model Catalog - 03-08-2025 02:49

---

model_catalog.json
script_output.log

- **New models added:** 62
- **Total models in catalog:** 244

🤖 Auto-update Model Catalog - 04-08-2025 02:50

---

model_catalog.json
script_output.log

- **New models added:** 78
- **Total models in catalog:** 283

🤖 Auto-update Model Catalog - 09-08-2025 02:35

---

model_catalog.json
script_output.log

- **New models added:** 82
- **Total models in catalog:** 305

🤖 Auto-update Model Catalog - 12-08-2025 09:02

---

model_catalog.json
script_output.log

- **New models added:** 75
- **Total models in catalog:** 314

🤖 Auto-update Model Catalog - 15-08-2025 02:37

---

model_catalog.json
script_output.log

- **New models added:** 64
- **Total models in catalog:** 323

🤖 Auto-update Model Catalog - 19-08-2025 02:33

---

model_catalog.json
script_output.log

- **New models added:** 67
- **Total models in catalog:** 343

🤖 Auto-update Model Catalog - 27-08-2025 14:07

---

model_catalog.json
script_output.log

- **New models added:** 76
- **Total models in catalog:** 349

🤖 Auto-update Model Catalog - 29-08-2025 02:31

---

model_catalog.json
script_output.log

- **New models added:** 77
- **Total models in catalog:** 351

🤖 Auto-update Model Catalog - 30-08-2025 02:29

---

model_catalog.json
script_output.log

- **New models added:** 70
- **Total models in catalog:** 353

🤖 Auto-update Model Catalog - 31-08-2025 02:32

---

model_catalog.json
script_output.log

- **New models added:** 66
- **Total models in catalog:** 360

🤖 Auto-update Model Catalog - 02-09-2025 02:32

---

model_catalog.json
script_output.log

- **New models added:** 68
- **Total models in catalog:** 374

🤖 Auto-update Model Catalog - 04-09-2025 02:28

---

model_catalog.json
script_output.log

- **New models added:** 78
- **Total models in catalog:** 385

🤖 Auto-update Model Catalog - 05-09-2025 04:02

---

model_catalog.json
script_output.log

- **New models added:** 72
- **Total models in catalog:** 393

🤖 Auto-update Model Catalog - 07-09-2025 02:31

---

model_catalog.json
script_output.log

- **New models added:** 56
- **Total models in catalog:** 357

🤖 Auto-update Model Catalog - 13-09-2025 02:23

---

model_catalog.json
script_output.log

- **New models added:** 57
- **Total models in catalog:** 358

🤖 Auto-update Model Catalog - 14-09-2025 02:31

---

model_catalog.json
script_output.log

- **New models added:** 60
- **Total models in catalog:** 366

🤖 Auto-update Model Catalog - 16-09-2025 02:28

---

model_catalog.json
script_output.log

- **New models added:** 57
- **Total models in catalog:** 370

🤖 Auto-update Model Catalog - 17-09-2025 02:29

---

model_catalog.json
script_output.log

- **New models added:** 62
- **Total models in catalog:** 375

🤖 Auto-update Model Catalog - 18-09-2025 10:04

---

model_catalog.json
script_output.log

- **New models added:** 56
- **Total models in catalog:** 382

🤖 Auto-update Model Catalog - 20-09-2025 02:27

---

model_catalog.json
script_output.log

- **New models added:** 57
- **Total models in catalog:** 399

🤖 Auto-update Model Catalog - 24-09-2025 02:29

---

model_catalog.json
script_output.log

- **New models added:** 63
- **Total models in catalog:** 410

🤖 Auto-update Model Catalog - 25-09-2025 02:30

---

model_catalog.json
script_output.log

- **New models added:** 73
- **Total models in catalog:** 425

🤖 Auto-update Model Catalog - 27-09-2025 02:26

---

model_catalog.json
script_output.log

- **New models added:** 76
- **Total models in catalog:** 428

🤖 Auto-update Model Catalog - 28-09-2025 02:33

---

model_catalog.json
script_output.log

- **New models added:** 71
- **Total models in catalog:** 454

🤖 Auto-update Model Catalog - 03-10-2025 02:28

---

model_catalog.json
script_output.log

- **New models added:** 82
- **Total models in catalog:** 475

🤖 Auto-update Model Catalog - 07-10-2025 02:29
